version: '3.8'
services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./:/home/gymlink_backend
    networks:
      - GymLink_network
    command: sh -c "npm install && npm run dev"

  database:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=POC_gimlink 
      - POSTGRES_USER=GymLink         
      - POSTGRES_DB=gymlink_db        
    networks:
      - GymLink_network
      
networks:
  GymLink_network:
    driver: bridge